version: '3'

services:
  seek-db:
    image: postgres:11
    container_name: n4h-lap-seek-db
    restart: always
    stop_grace_period: 1m30s
    env_file:
      - docker-compose.env
    volumes:
      - seek-db:/var/lib/postgresql/data

  seek:
    image: knoppiks/nfdi4health-lap-seek:latest

    container_name: n4h-lap-seek
    command: docker/entrypoint.sh
    restart: always
    environment:
      RAILS_ENV: "production"
      SOLR_PORT: "8983"
      SOLR_HOST: "solr"
      NO_ENTRYPOINT_WORKERS: "1"
    env_file:
      - docker-compose.env
    volumes:
      - seek-filestore:/seek/filestore
      - seek-cache:/seek/tmp/cache
    ports:
      - "3000:3000"
    depends_on:
      - seek-db
      - seek-solr
    links:
      - seek-db
      - seek-solr

  seek-workers:
    image: knoppiks/nfdi4health-lap-seek:latest
    container_name: n4h-lap-seek-workers
    command: docker/start_workers.sh
    restart: always
    environment:
      RAILS_ENV: "production"
      SOLR_PORT: "8983"
      SOLR_HOST: "seek-solr"
    env_file:
      - docker-compose.env
    volumes:
      - seek-filestore:/seek/filestore
      - seek-cache:/seek/tmp/cache
    depends_on:
      - seek-db
      - seek-solr
    links:
      - seek-db
      - seek-solr

  seek-solr:
    image: fairdom/seek-solr:8.9
    container_name: n4h-lap-seek-solr
    restart: always
    environment:
      SOLR_JAVA_MEM: "-Xms512m -Xmx1024m"
    volumes:
      - seek-solr-data:/var/solr/
    entrypoint: ["docker-entrypoint.sh", "solr-precreate", "seek", "/opt/solr/server/solr/configsets/seek_config"]

volumes:
  seek-db:
  seek-cache:
  seek-filestore:
  seek-solr-data:
